### ISSUE TITLE
list of errors found during testing branch develop

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#1091]
**errors are**
 
- [x] arduino: wrong code generated for math function abs. absD is missing. I will commit this change today.
- [x] bob3: the block "begrenze" generates wrong code (uses rob.clamp instead of myBob.clamp)
- [x] calliope: "text anhängen" geenrates code as s += ManagedString(ManagedString("")); and this fails
- [x] calliope: code generated for block "remove first from list" lacks a final ";" (maybe more ; missing)
- [x] calliope: find first/last does not work with Images and Colours - != is not found for both classes
- [x] botnroll: showing colours on lcd tries to get the c_str from an unsigned int
- [x] botnroll: button sensors produces LEFT/RIGHT/ENTER/ANY instead of 1/2/3/123
- [x] botnroll: programs that use motors (everything from Drive and Move categories) cannot produce code. One of the reasons is that medium motors do not have a side, that the code generation expects #1094 
- [x] ev3: Invalid modes (wait block) - IRSEEKER_MODULATED, IRSEEKER_UNMODULATED, 
COMPASS_COMPASS
- [x] ev3: medium motors do not work, since they do not provide the side (No property with name MOTOR_DRIVE) #1094 
- [x] ev3 and nxt: other power consumer does not work, it is treated as a motor (No property with name MOTOR_REVERSE) #1094 
- [x] mbot: typo in the geared motor configuration block (grared motor)

**to consider**

- [x] Artem detected a problem with "`compass_compass`" sensor (mode)
- [x] the key "`Key.LIST_CREATE_WITH_ERROR`" is a very special case for nxt. Really needed? YES
- test programs become _very_ soon too large for bob3
