### ISSUE TITLE
NXT Integration

### ISSUE THREAD

**Issue by BeateJ** [OpenRoberta/robertalab#127]
- [x] NXC code generation #128 #131

- [x] NXT brick configuration #129

- [x] NXT compiler workflow #130

- [x] GUI switch between different robot systems #143

- [x] GUI blocks and toolbox #150

- [x] Adopt simulation for NXT #237

- [x] Provide / adopt USB program #38 

- [ ] Check if bluetooth can be used

- [ ] Provide / adopt chromeapp to connect and communicate with NXT #180
