### ISSUE TITLE
Arduino Integration

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#167]
Currently we have several arduino based robot systems, that we would like to support. As a first step we will create the basic code generation for arduinos, later a this robot plugin can be devided into several specific systems, e.g. BAYDUINO, mcookies, Bot'n Roll ...

https://www.arduino.cc/en/Reference/HomePage
- [x] Arduino code generation  #196
- [x] Arduino compiler workflow  #199
- [x] Provide / adopt USB program  OpenRoberta/robertalab-usbprogram#5
- [ ] Check if bluetooth can be used
- [x] Extend / adopt GUI and blockly #224  #197
