### ISSUE TITLE
As a kid I would like to create programs for the micro:bit and calliope with the Open Roberta Lab

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#271]
- [x] micro:bit code generation  -> python https://www.python.org/community/microbit/, #274
- [ ] micro:bit brick configuration -> switch between 2 fixed configurations micro:bit and calliope #272
- [x] micro:bit compiler workflow 
- [x] GUI blocks and toolbox  -> no switch to event based blocks necessary, but can be extended #272
- [x] Adopt simulation for micro:bit / calliope #315
- [x] micro:bit download workflow #276

Due to some time limits this task should concentrate on micro:bit functionality and should be extended later for the special calliope sensors and actors. We expect that all micro:bit functions  are working on calliope similarly.

**Comment by bjost2s** [comment]
should be reopened, if we start providing blocks for external sensors
