### ISSUE TITLE
NAO Implementation

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab#310]
- [x] NAO code generation #346 
- [x] NAO brick configuration (information tab) #347
- [x] GUI blocks and toolbox #348
- [x] Symbol for NAO #349
- [x] Provide connection program #350
- [x] NAO code cleanup #359 
- [x] Add NAO background #365 
- [x] Add symbols for new NAO toolboxes #371

**Comment by bjost2s** [comment]
please provide a similar description of the NAO integration as we did it for the other robot systems. e.g. #127 and split the different task into sub tickets
