### ISSUE TITLE
Arduino (Uno, Mega, Nano, etc.)  and compatible board integration

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#745]
Integration of Arduino (Uno, Mega, Nano, etc.)  and compatible boards, e.g. Funduino: https://funduino.de/.

 - [x] check which boards are compatible, e.g. Uno, Mega, ...
 - [x] Arduino code generation #755
 - [x] Arduino tests #846
 - [x] Arduino configuration #756 
 - [x] Arduino GUI blocks and toolbox #817
 - [x] Arduino compiler workflow #847 
 - [x] Arduino choice #979
