### ISSUE TITLE
Arduino (Uno, Mega, Nano, etc.)  code generation

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#755]
Code generation for the board from issue #745 
- [x]  Implement backend configuration blocks #845
- [x]  Implement backend new sensor blocks #844
- [x]  Implement backend new actor blocks #917
- [x] Read and generate name, pins and ports from configuration
- [x] Generate code from program blocks with the names synchronized with configuration #848 
- [x]  Add a program checker #946
