### ISSUE TITLE
WeDo plugin

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#918]
- [ ] create a new project for the WeDo plugin and make code generation for WeDo available #919
- [ ] create blocks and configuration blocks #914 
- [ ] connect via webview #893
- [ ] create an app for Android and IOS to execute the generated code on WeDo via a Smartphone / Tablet
- [ ] create a desktop app to execute the generated code from a computer
